create schema if not exists data;
create schema if not exists ppd;

--#############################################################

CREATE TABLE IF NOT EXISTS data.vehicle_type(
                                                  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                      START WITH
                                                          1
                                                      ),
                                                  type_name VARCHAR(100) NOT NULL,
                                                  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS data.vehicle_manufacturer(
                                                          id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                              START WITH
                                                                  1
                                                              ),
                                                          company_name VARCHAR(100) NOT NULL,
                                                          PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS data.vehicle_model(
                                                   id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                       START WITH
                                                           1
                                                       ),
                                                   manufacturer_id BIGINT NOT NULL,
                                                   manufacture_code varchar(255),
                                                   max_passenger_count SMALLINT NOT null,
                                                   max_distance SMALLINT NOT NULL,
                                                   max_pilot_count SMALLINT NOT NULL,
                                                   lift_capacity bigint NOT NULL,
                                                   model_name varchar(255) NOT NULL,
                                                   PRIMARY KEY(id),
                                                   FOREIGN KEY(manufacturer_id) REFERENCES data.vehicle_manufacturer(id)
);

CREATE TABLE IF NOT EXISTS data.vehicle(
                                             id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                 START WITH
                                                     1
                                                 ),
                                             vehicle_type_id BIGINT NOT NULL,
                                             vehicle_model_id BIGINT NOT NULL,
                                             next_maintenance_date DATE CHECK(next_maintenance_date >= current_date),
                                             friendly_name VARCHAR(100),
                                             rent_date date,
                                             PRIMARY KEY(id),
                                             FOREIGN KEY(vehicle_type_id) REFERENCES data.vehicle_type(id),
                                             FOREIGN KEY(vehicle_model_id) REFERENCES data.vehicle_model(id)
);

CREATE TABLE IF NOT EXISTS data.nationality(
                                                 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                     START WITH
                                                         1
                                                     ),
                                                 name VARCHAR(100) NOT NULL,
                                                 PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS data.city(
                                          id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                              START WITH
                                                  1
                                              ),
                                          nationality_id bigint NOT NULL,
                                          name VARCHAR(100) NOT NULL,
                                          PRIMARY KEY(id),
                                          FOREIGN KEY(nationality_id) REFERENCES data.nationality(id)
);

CREATE TABLE IF NOT EXISTS data.route(
                                           id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                               START WITH
                                                   1
                                               ),
                                           source_city_id bigint NOT NULL,
                                           destination_city_id bigint NOT NULL UNIQUE,
                                           distance bigint NOT NULL UNIQUE,
                                           PRIMARY KEY(id),
                                           FOREIGN KEY(source_city_id) REFERENCES data.city(id),
                                           FOREIGN KEY(destination_city_id) REFERENCES data.city(id)
);

CREATE TABLE IF NOT EXISTS data.schedule(
                                              id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                  START WITH
                                                      1
                                                  ),
                                              expiration_date TIMESTAMP WITH TIME ZONE NOT NULL,
                                              name varchar(100) NOT NULL,
                                              PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS data.explicit_flight_interval(
                                                              id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                                  START WITH
                                                                      1
                                                                  ),
                                                              schedule_id bigint NOT NULL,
                                                              planned_departure_timestampt TIMESTAMP WITH TIME ZONE NOT NULL,
                                                              planned_arrival_timestampt TIMESTAMP WITH TIME ZONE NOT NULL,
                                                              CHECK(planned_departure_timestampt <= planned_arrival_timestampt),
                                                              PRIMARY KEY(id),
                                                              FOREIGN KEY(schedule_id) REFERENCES data.schedule(id)
);

CREATE TABLE IF NOT EXISTS data.cyclic_flight_interval(
                                                            id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                                START WITH
                                                                    1
                                                                ),
                                                            departure_cron_expression varchar(30),
                                                            arrival_cron_expression varchar(30),
                                                            PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS data.cyclic_interval_to_schedule(
                                                                 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                                     START WITH
                                                                         1
                                                                     ),
                                                                 schedule_id bigint NOT NULL,
                                                                 interval_id bigint NOT NULL,
                                                                 PRIMARY KEY(id),
                                                                 FOREIGN KEY(schedule_id) REFERENCES data.schedule(id),
                                                                 FOREIGN KEY(interval_id) REFERENCES data.cyclic_flight_interval(id)
);

CREATE TABLE IF NOT EXISTS data.schedule_route(
                                                    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                        START WITH
                                                            1
                                                        ),
                                                    schedule_id bigint NOT NULL,
                                                    route_id bigint NOT NULL,
                                                    PRIMARY KEY(id),
                                                    FOREIGN KEY(schedule_id) REFERENCES data.schedule(id),
                                                    FOREIGN KEY(route_id) REFERENCES data.route(id)
);

CREATE TABLE IF NOT EXISTS data.flight(
                                            id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                START WITH
                                                    1
                                                ),
                                            route_id bigint NOT NULL,
                                            vehicle_id bigint NOT NULL,
                                            generated_from_schedule_id bigint,
                                            active boolean NOT NULL DEFAULT FALSE,
                                            flight_number text NOT NULL,
                                            available_passengers_seats SMALLINT NOT NULL,
                                            min_pilot_count SMALLINT NOT NULL,
                                            confidential bool NOT NULL,
                                            last_modification_date TIMESTAMP WITH TIME ZONE NOT NULL CHECK(last_modification_date <= now()),
                                            archival boolean NOT NULL DEFAULT FALSE,
                                            planned_departure TIMESTAMP WITH TIME ZONE NOT NULL,
                                            planned_arrival TIMESTAMP WITH TIME ZONE NOT NULL,
                                            CHECK(planned_departure <= planned_arrival),
                                            PRIMARY KEY(id),
                                            FOREIGN KEY(route_id) REFERENCES data.route(id),
                                            FOREIGN KEY(vehicle_id) REFERENCES data.vehicle(id),
                                            FOREIGN KEY(generated_from_schedule_id) REFERENCES data.schedule(id)
);


CREATE TABLE IF NOT EXISTS ppd.employee_role(
                                                id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                    START WITH
                                                        1
                                                    ),
                                                role VARCHAR(50),
                                                PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS ppd.employee_account_data(
                                                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                            START WITH
                                                                1
                                                            ),
                                                        login TEXT,
                                                        password TEXT,
                                                        PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS ppd.role_to_employee(
                                                   id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                       START WITH
                                                           1
                                                       ),
                                                   role_id BIGINT NOT NULL,
                                                   employee_account_id BIGINT NOT NULL,
                                                   assigned_date TIMESTAMP WITH TIME ZONE CHECK(assigned_date <= now()),
                                                   PRIMARY KEY(id),
                                                   FOREIGN KEY(role_id) REFERENCES ppd.employee_role(id),
                                                   FOREIGN KEY(employee_account_id) REFERENCES ppd.employee_account_data(id)
);

CREATE TABLE IF NOT EXISTS ppd.employee(
                                           id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                               START WITH
                                                   1
                                               ),
                                           first_name varchar(100) NOT NULL,
                                           last_name varchar(100) NOT NULL,
                                           employment_date date NOT NULL,
                                           PRIMARY KEY(id),
                                           FOREIGN KEY(id) REFERENCES ppd.employee_account_data(id)
);

CREATE TABLE IF NOT EXISTS ppd.pilot_status(
                                               id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                   START WITH
                                                       1
                                                   ),
                                               status VARCHAR(50),
                                               PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS ppd.pilot(
                                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                            START WITH
                                                1
                                            ),
                                        nationality_id BIGINT NOT NULL,
                                        pilot_status_id BIGINT NOT NULL,
                                        license_number text NOT NULL,
                                        hours_flown smallint NOT NULL,
                                        PRIMARY KEY(id),
                                        FOREIGN KEY(id) REFERENCES ppd.employee(id),
                                        FOREIGN KEY(nationality_id) REFERENCES data.nationality(id),
                                        FOREIGN KEY(pilot_status_id) REFERENCES ppd.pilot_status(id)
);

CREATE TABLE IF NOT EXISTS ppd.vehicle_model_pilot_preferation(
                                                                  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                                      START WITH
                                                                          1
                                                                      ),
                                                                  pilot_id BIGINT NOT NULL,
                                                                  vehicle_model_id BIGINT NOT NULL,
                                                                  PRIMARY KEY(id),
                                                                  FOREIGN KEY(vehicle_model_id) REFERENCES data.vehicle_model(id),
                                                                  FOREIGN KEY(pilot_id) REFERENCES ppd.pilot(id)
);

CREATE TABLE IF NOT EXISTS ppd.customer(
                                           id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                               START WITH
                                                   1
                                               ),
                                           first_name varchar(100) NOT NULL,
                                           last_name varchar(100) NOT NULL,
                                           password text NOT NULL,
                                           email varchar(100) NOT NULL UNIQUE,
                                           phone varchar(20),
                                           registration_date TIMESTAMP WITH TIME ZONE NOT NULL CHECK(registration_date <= now()),
                                           PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS data.reservation(
                                                 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                     START WITH
                                                         1
                                                     ),
                                                 customer_id bigint NOT NULL,
                                                 flight_id bigint NOT NULL,
                                                 reservation_number text NOT NULL UNIQUE,
                                                 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                                 PRIMARY KEY(id),
                                                 FOREIGN KEY(customer_id) REFERENCES ppd.customer(id),
                                                 FOREIGN KEY(flight_id) REFERENCES data.flight(id)
);

CREATE TABLE IF NOT EXISTS ppd.passenger(
                                            id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                START WITH
                                                    1
                                                ),
                                            reservation_id bigint NOT NULL,
                                            nationality_id bigint NOT NULL,
                                            first_name varchar(100) NOT NULL,
                                            last_name varchar(100) NOT NULL,
                                            adult boolean NOT NULL,
                                            PRIMARY KEY(id),
                                            FOREIGN KEY(reservation_id) REFERENCES data.reservation(id),
                                            FOREIGN KEY(nationality_id) REFERENCES data.nationality(id)
);

CREATE TABLE IF NOT EXISTS data.flight_pilot(
                                                  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                                      START WITH
                                                          1
                                                      ),
                                                  pilot_id bigint NOT NULL,
                                                  flight_id bigint NOT NULL,
                                                  assigned_by_employee_id bigint NOT NULL,
                                                  assigned_date TIMESTAMP WITH TIME ZONE NOT NULL CHECK(assigned_date <= now()),
                                                  PRIMARY KEY(id),
                                                  FOREIGN KEY(pilot_id) REFERENCES ppd.pilot(id),
                                                  FOREIGN KEY(assigned_by_employee_id) REFERENCES ppd.employee(id),
                                                  FOREIGN KEY(flight_id) REFERENCES data.flight(id)
);